# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatsremaining',
            name='caste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caste_seats', to='vacancy.Caste'),
        ),
        migrations.AlterField(
            model_name='seatsremaining',
            name='clg_dept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clg_dept_seats', to='vacancy.CollegeDepartment'),
        ),
        migrations.AlterField(
            model_name='seatsremaining',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
